baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'PaperMod'
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
  [[menu.main]]
    name = "About"
    url = "/about/"
  [[menu.main]]
    name = "Projects"
    url = "/projects/"